// Byte-for-byte SVG snapshots generated by Python fixtures in the Monty sandbox.

import { mkdtemp, readFile, realpath, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { runSandboxCode } from "./monty-sandbox";

/** Python fixture and expected SVG names for one plot snapshot. */
interface PlotSnapshotCase {
    /** Description shown in Vitest output. */
    name: string;
    /** Python fixture executed by the Monty sandbox. */
    scriptName: string;
    /** SVG file generated by the fixture and stored as its expected snapshot. */
    snapshotName: string;
}

const PLOT_SNAPSHOT_DIRECTORY = resolve(
    import.meta.dirname,
    "../../tests/plot-snapshots",
);

const PLOT_SNAPSHOT_CASES: PlotSnapshotCase[] = [
    {
        name: "scatter plot",
        scriptName: "scatter-plot.py",
        snapshotName: "scatter-plot.svg",
    },
    {
        name: "histogram",
        scriptName: "histogram-plot.py",
        snapshotName: "histogram-plot.svg",
    },
];

describe("Monty plot snapshots", () => {
    it.each(
        PLOT_SNAPSHOT_CASES,
    )("$name Python fixture reproduces its SVG byte-for-byte", async ({
        name,
        scriptName,
        snapshotName,
    }) => {
        const rawOutputDirectory = await mkdtemp(
            join(tmpdir(), "monty-plot-snapshot-"),
        );
        const outputDirectory = await realpath(rawOutputDirectory);

        try {
            const code = await readFile(
                join(PLOT_SNAPSHOT_DIRECTORY, scriptName),
                "utf-8",
            );
            const result = await runSandboxCode(code, outputDirectory);
            if (!result.success) {
                throw new Error(
                    `Monty plot fixture failed: ${result.errorType}: ${result.message}`,
                );
            }

            const actual = await readFile(join(outputDirectory, snapshotName));
            const expected = await readFile(
                join(PLOT_SNAPSHOT_DIRECTORY, snapshotName),
            );
            expect(
                actual.equals(expected),
                `${name} fixture SVG mismatch: expected ${expected.byteLength} bytes, received ${actual.byteLength} bytes`,
            ).toBe(true);
        } finally {
            await rm(outputDirectory, { recursive: true, force: true });
        }
    });
});
